name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
      GKE_REGION: ${{ secrets.GKE_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build and push api-users Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/imperial-terra-461008-s5/gcr/api-users:$GITHUB_SHA .
          docker push asia-southeast1-docker.pkg.dev/imperial-terra-461008-s5/gcr/api-users:$GITHUB_SHA


  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
      GKE_REGION: ${{ secrets.GKE_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy api-users to GKE
        run: |
          kubectl set image deployment/api-users api-users=asia-southeast1-docker.pkg.dev/$GCP_PROJECT_ID/gcr/api-users:$GITHUB_SHA
          kubectl rollout status deployment/api-users