name: Build and Deploy to GKE

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Build and push Docker images
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Google Cloud (using GitHub secret GCP_CREDENTIALS)
      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configure Docker to use GCR (Google Container Registry)
      - name: Set up Docker to use GCR
        run: |
          gcloud auth configure-docker gcr.io

      # Build and push Docker image for api-users
      - name: Build and push api-users Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/api-users:$GITHUB_SHA ./api-users
          docker push gcr.io/$GCP_PROJECT_ID/api-users:$GITHUB_SHA

  # Deploy to GKE
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deployment runs only after the build job is successful

    steps:
      # Checkout the repository again in the deploy job
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Google Cloud credentials
      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configure kubectl
      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_REGION
          kubectl config set-context --current --namespace=default

      # Update deployment for api-users
      - name: Deploy api-users to GKE
        run: |
          kubectl set image deployment/api-users api-users=gcr.io/$GCP_PROJECT_ID/api-users:$GITHUB_SHA
          kubectl rollout status deployment/api-users
